### ISSUE TITLE
#2 : Creating An Issue.

### ISSUE THREAD

**Issue by Torotv** [Torotv/JvaUI#2]
> While Creating An issue, Please Say The issue and Operting System And WHat Type. And Please add The Label Help, Also Add The Milestone First docs and Assign Yourself ( if Possible).
ex.

Name: @Greenbayrules
Date: sept 23
OS: MACOS
Prompblem: Not Working Throuhgh Linuk
![code](https://user-images.githubusercontent.com/21000033/30725214-0510c202-9f11-11e7-969f-70e4a65c14bd.png)

**Comment by GreenBayRules** [comment]
Huh, do you mean Linux?

**Comment by Torotv** [comment]
Yeah!
